package com.cmj.example.mapper;

import com.cmj.example.base.FundUserBase;
import com.cmj.example.base.FundUserBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundUserBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    long countByExample(FundUserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    int insert(FundUserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") FundUserBase record, @Param("selective") FundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    FundUserBase selectOneByExample(FundUserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    FundUserBase selectOneByExampleSelective(@Param("example") FundUserBaseExample example, @Param("selective") FundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    List<FundUserBase> selectByExampleSelective(@Param("example") FundUserBaseExample example, @Param("selective") FundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    List<FundUserBase> selectByExample(FundUserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    FundUserBase selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") FundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    FundUserBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FundUserBase record, @Param("example") FundUserBaseExample example, @Param("selective") FundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FundUserBase record, @Param("example") FundUserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") FundUserBase record, @Param("selective") FundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FundUserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<FundUserBase> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_funduser
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<FundUserBase> list, @Param("selective") FundUserBase.Column ... selective);
}