package com.cmj.example.mapper;

import com.cmj.example.base.FundTypeBase;
import com.cmj.example.base.FundTypeBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundTypeBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    long countByExample(FundTypeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    int insert(FundTypeBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") FundTypeBase record, @Param("selective") FundTypeBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    FundTypeBase selectOneByExample(FundTypeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    FundTypeBase selectOneByExampleSelective(@Param("example") FundTypeBaseExample example, @Param("selective") FundTypeBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    List<FundTypeBase> selectByExampleSelective(@Param("example") FundTypeBaseExample example, @Param("selective") FundTypeBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    List<FundTypeBase> selectByExample(FundTypeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    FundTypeBase selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") FundTypeBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    FundTypeBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FundTypeBase record, @Param("example") FundTypeBaseExample example, @Param("selective") FundTypeBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FundTypeBase record, @Param("example") FundTypeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") FundTypeBase record, @Param("selective") FundTypeBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FundTypeBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<FundTypeBase> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_type
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<FundTypeBase> list, @Param("selective") FundTypeBase.Column ... selective);
}