package com.cmj.example.mapper;

import com.cmj.example.base.FundHasFundUserBase;
import com.cmj.example.base.FundHasFundUserBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundHasFundUserBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    long countByExample(FundHasFundUserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    int insert(FundHasFundUserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") FundHasFundUserBase record, @Param("selective") FundHasFundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    FundHasFundUserBase selectOneByExample(FundHasFundUserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    FundHasFundUserBase selectOneByExampleSelective(@Param("example") FundHasFundUserBaseExample example, @Param("selective") FundHasFundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    List<FundHasFundUserBase> selectByExampleSelective(@Param("example") FundHasFundUserBaseExample example, @Param("selective") FundHasFundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    List<FundHasFundUserBase> selectByExample(FundHasFundUserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    FundHasFundUserBase selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") FundHasFundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    FundHasFundUserBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FundHasFundUserBase record, @Param("example") FundHasFundUserBaseExample example, @Param("selective") FundHasFundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FundHasFundUserBase record, @Param("example") FundHasFundUserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") FundHasFundUserBase record, @Param("selective") FundHasFundUserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FundHasFundUserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<FundHasFundUserBase> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fund_has_funduser
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<FundHasFundUserBase> list, @Param("selective") FundHasFundUserBase.Column ... selective);
}