package com.cmj.example.mapper;

import com.cmj.example.base.IndustrBase;
import com.cmj.example.base.IndustrBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndustrBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    long countByExample(IndustrBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    int insert(IndustrBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") IndustrBase record, @Param("selective") IndustrBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    IndustrBase selectOneByExample(IndustrBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    IndustrBase selectOneByExampleSelective(@Param("example") IndustrBaseExample example, @Param("selective") IndustrBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    List<IndustrBase> selectByExampleSelective(@Param("example") IndustrBaseExample example, @Param("selective") IndustrBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    List<IndustrBase> selectByExample(IndustrBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    IndustrBase selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") IndustrBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    IndustrBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IndustrBase record, @Param("example") IndustrBaseExample example, @Param("selective") IndustrBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IndustrBase record, @Param("example") IndustrBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") IndustrBase record, @Param("selective") IndustrBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndustrBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<IndustrBase> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_industry
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<IndustrBase> list, @Param("selective") IndustrBase.Column ... selective);
}