package com.cmj.example.mapper;

import com.cmj.example.base.StockBase;
import com.cmj.example.base.StockBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StockBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    long countByExample(StockBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    int insert(StockBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") StockBase record, @Param("selective") StockBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    StockBase selectOneByExample(StockBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    StockBase selectOneByExampleSelective(@Param("example") StockBaseExample example, @Param("selective") StockBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    List<StockBase> selectByExampleSelective(@Param("example") StockBaseExample example, @Param("selective") StockBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    List<StockBase> selectByExample(StockBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    StockBase selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") StockBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    StockBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StockBase record, @Param("example") StockBaseExample example, @Param("selective") StockBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StockBase record, @Param("example") StockBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") StockBase record, @Param("selective") StockBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StockBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<StockBase> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_stock
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<StockBase> list, @Param("selective") StockBase.Column ... selective);
}