package com.cmj.example.mapper;

import com.cmj.example.base.UserBase;
import com.cmj.example.base.UserBaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    long countByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    int insert(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    int insertSelective(@Param("record") UserBase record, @Param("selective") UserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    UserBase selectOneByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    UserBase selectOneByExampleSelective(@Param("example") UserBaseExample example, @Param("selective") UserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    List<UserBase> selectByExampleSelective(@Param("example") UserBaseExample example, @Param("selective") UserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    List<UserBase> selectByExample(UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    UserBase selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") UserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    UserBase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserBase record, @Param("example") UserBaseExample example, @Param("selective") UserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserBase record, @Param("example") UserBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(@Param("record") UserBase record, @Param("selective") UserBase.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    int batchInsert(@Param("list") List<UserBase> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_user
     *
     * @mbg.generated
     */
    int batchInsertSelective(@Param("list") List<UserBase> list, @Param("selective") UserBase.Column ... selective);
}