package com.cmj.example.base;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class FundEntryBase implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FId
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FFundId
     *
     * @mbg.generated
     */
    private String fundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FStockNumber
     *
     * @mbg.generated
     */
    private String stockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FStockNamer
     *
     * @mbg.generated
     */
    private String stockNamer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FRate
     *
     * @mbg.generated
     */
    private BigDecimal rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FCreateTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FUpdateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FDeleteTime
     *
     * @mbg.generated
     */
    private Date deleteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FCreator
     *
     * @mbg.generated
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FUpdater
     *
     * @mbg.generated
     */
    private Integer updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FDeleter
     *
     * @mbg.generated
     */
    private Integer deleter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_base_fundentry.FIsDelete
     *
     * @mbg.generated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_base_fundentry
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FId
     *
     * @return the value of t_base_fundentry.FId
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FId
     *
     * @param id the value for t_base_fundentry.FId
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FFundId
     *
     * @return the value of t_base_fundentry.FFundId
     *
     * @mbg.generated
     */
    public String getFundId() {
        return fundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FFundId
     *
     * @param fundId the value for t_base_fundentry.FFundId
     *
     * @mbg.generated
     */
    public void setFundId(String fundId) {
        this.fundId = fundId == null ? null : fundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FStockNumber
     *
     * @return the value of t_base_fundentry.FStockNumber
     *
     * @mbg.generated
     */
    public String getStockNumber() {
        return stockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FStockNumber
     *
     * @param stockNumber the value for t_base_fundentry.FStockNumber
     *
     * @mbg.generated
     */
    public void setStockNumber(String stockNumber) {
        this.stockNumber = stockNumber == null ? null : stockNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FStockNamer
     *
     * @return the value of t_base_fundentry.FStockNamer
     *
     * @mbg.generated
     */
    public String getStockNamer() {
        return stockNamer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FStockNamer
     *
     * @param stockNamer the value for t_base_fundentry.FStockNamer
     *
     * @mbg.generated
     */
    public void setStockNamer(String stockNamer) {
        this.stockNamer = stockNamer == null ? null : stockNamer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FRate
     *
     * @return the value of t_base_fundentry.FRate
     *
     * @mbg.generated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FRate
     *
     * @param rate the value for t_base_fundentry.FRate
     *
     * @mbg.generated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FCreateTime
     *
     * @return the value of t_base_fundentry.FCreateTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FCreateTime
     *
     * @param createTime the value for t_base_fundentry.FCreateTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FUpdateTime
     *
     * @return the value of t_base_fundentry.FUpdateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FUpdateTime
     *
     * @param updateTime the value for t_base_fundentry.FUpdateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FDeleteTime
     *
     * @return the value of t_base_fundentry.FDeleteTime
     *
     * @mbg.generated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FDeleteTime
     *
     * @param deleteTime the value for t_base_fundentry.FDeleteTime
     *
     * @mbg.generated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FCreator
     *
     * @return the value of t_base_fundentry.FCreator
     *
     * @mbg.generated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FCreator
     *
     * @param creator the value for t_base_fundentry.FCreator
     *
     * @mbg.generated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FUpdater
     *
     * @return the value of t_base_fundentry.FUpdater
     *
     * @mbg.generated
     */
    public Integer getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FUpdater
     *
     * @param updater the value for t_base_fundentry.FUpdater
     *
     * @mbg.generated
     */
    public void setUpdater(Integer updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FDeleter
     *
     * @return the value of t_base_fundentry.FDeleter
     *
     * @mbg.generated
     */
    public Integer getDeleter() {
        return deleter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FDeleter
     *
     * @param deleter the value for t_base_fundentry.FDeleter
     *
     * @mbg.generated
     */
    public void setDeleter(Integer deleter) {
        this.deleter = deleter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_base_fundentry.FIsDelete
     *
     * @return the value of t_base_fundentry.FIsDelete
     *
     * @mbg.generated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_base_fundentry.FIsDelete
     *
     * @param isDelete the value for t_base_fundentry.FIsDelete
     *
     * @mbg.generated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fundentry
     *
     * @mbg.generated
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_base_fundentry
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fundId=").append(fundId);
        sb.append(", stockNumber=").append(stockNumber);
        sb.append(", stockNamer=").append(stockNamer);
        sb.append(", rate=").append(rate);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", creator=").append(creator);
        sb.append(", updater=").append(updater);
        sb.append(", deleter=").append(deleter);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_base_fundentry
     *
     * @mbg.generated
     */
    public static class Builder {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        private FundEntryBase obj;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public Builder() {
            this.obj = new FundEntryBase();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FId
         *
         * @param id the value for t_base_fundentry.FId
         *
         * @mbg.generated
         */
        public Builder id(Integer id) {
            obj.setId(id);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FFundId
         *
         * @param fundId the value for t_base_fundentry.FFundId
         *
         * @mbg.generated
         */
        public Builder fundId(String fundId) {
            obj.setFundId(fundId);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FStockNumber
         *
         * @param stockNumber the value for t_base_fundentry.FStockNumber
         *
         * @mbg.generated
         */
        public Builder stockNumber(String stockNumber) {
            obj.setStockNumber(stockNumber);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FStockNamer
         *
         * @param stockNamer the value for t_base_fundentry.FStockNamer
         *
         * @mbg.generated
         */
        public Builder stockNamer(String stockNamer) {
            obj.setStockNamer(stockNamer);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FRate
         *
         * @param rate the value for t_base_fundentry.FRate
         *
         * @mbg.generated
         */
        public Builder rate(BigDecimal rate) {
            obj.setRate(rate);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FCreateTime
         *
         * @param createTime the value for t_base_fundentry.FCreateTime
         *
         * @mbg.generated
         */
        public Builder createTime(Date createTime) {
            obj.setCreateTime(createTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FUpdateTime
         *
         * @param updateTime the value for t_base_fundentry.FUpdateTime
         *
         * @mbg.generated
         */
        public Builder updateTime(Date updateTime) {
            obj.setUpdateTime(updateTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FDeleteTime
         *
         * @param deleteTime the value for t_base_fundentry.FDeleteTime
         *
         * @mbg.generated
         */
        public Builder deleteTime(Date deleteTime) {
            obj.setDeleteTime(deleteTime);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FCreator
         *
         * @param creator the value for t_base_fundentry.FCreator
         *
         * @mbg.generated
         */
        public Builder creator(Integer creator) {
            obj.setCreator(creator);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FUpdater
         *
         * @param updater the value for t_base_fundentry.FUpdater
         *
         * @mbg.generated
         */
        public Builder updater(Integer updater) {
            obj.setUpdater(updater);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FDeleter
         *
         * @param deleter the value for t_base_fundentry.FDeleter
         *
         * @mbg.generated
         */
        public Builder deleter(Integer deleter) {
            obj.setDeleter(deleter);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method sets the value of the database column t_base_fundentry.FIsDelete
         *
         * @param isDelete the value for t_base_fundentry.FIsDelete
         *
         * @mbg.generated
         */
        public Builder isDelete(Integer isDelete) {
            obj.setIsDelete(isDelete);
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public FundEntryBase build() {
            return this.obj;
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_base_fundentry
     *
     * @mbg.generated
     */
    public enum Column {
        id("FId", "id", "INTEGER", false),
        fundId("FFundId", "fundId", "VARCHAR", false),
        stockNumber("FStockNumber", "stockNumber", "VARCHAR", false),
        stockNamer("FStockNamer", "stockNamer", "VARCHAR", false),
        rate("FRate", "rate", "DECIMAL", false),
        createTime("FCreateTime", "createTime", "TIMESTAMP", false),
        updateTime("FUpdateTime", "updateTime", "TIMESTAMP", false),
        deleteTime("FDeleteTime", "deleteTime", "TIMESTAMP", false),
        creator("FCreator", "creator", "INTEGER", false),
        updater("FUpdater", "updater", "INTEGER", false),
        deleter("FDeleter", "deleter", "INTEGER", false),
        isDelete("FIsDelete", "isDelete", "TINYINT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_base_fundentry
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}